### ISSUE TITLE
Does not show properly value of Prevent new users from creating new tags 

### ISSUE THREAD

**Issue by pedjas** [svivian/q2a-tagging-tools#18] opened 2017-05-15 09:43 UTC
I have option set to prevent users create new tags if user has less than 100 points. When I repoen plugin settings it shows like option is not set (but it is and is enforced)

Only after I submitted form several times, it started displaying properly. Not browser caching issue as I experienced problem few days after originally setting this option.

**Comment by svivian** [comment] 2017-05-30 10:43
Sorry for the late reply. I am unable to reproduce this problem. Can't think of any reason it would occur besides some issue with your browser or web server. If you are able to provide more details to reliably reproduce the problem then I may be able to fix it, for example any PHP or server errors that occur.

**Comment by pedjas** [comment] 2017-05-30 12:29
After I disabled and enabled few times it finally showed up correctly, and I cannot make it repeat.

However, at the end I left it disabled as for some reason, if user is unable to set tag he cannot post question at all.

**Comment by svivian** [comment] 2017-05-30 14:00
OK will close this for now.

BTW the latter bug you mention is been fixed today.

**Closed by svivian** 2017-05-30 14:00 UTC
